// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaTraction.Infrastructure.Persistence;

#nullable disable

namespace SistemaTraction.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602191124_AddSettingsKeys")]
    partial class AddSettingsKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaTraction.Domain.Config.AppConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Preço padrão de corte por peça (R$)",
                            IsDeleted = false,
                            Key = "cutting_price_default",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.00"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Preço padrão de costura por peça — tamanhos P/M/G/GG (R$)",
                            IsDeleted = false,
                            Key = "sewing_price_default",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5.60"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Preço de costura por peça — tamanho G1 (R$)",
                            IsDeleted = false,
                            Key = "sewing_price_g1",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "6.30"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Preço padrão por folha DTF (R$)",
                            IsDeleted = false,
                            Key = "dtf_sheet_price_default",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "49.80"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quantidade mínima em estoque antes de disparar alerta de reposição",
                            IsDeleted = false,
                            Key = "stock_alert_threshold",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "15"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dias de histórico usados para calcular recomendação de corte",
                            IsDeleted = false,
                            Key = "recommendation_days",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tamanhos disponíveis para produção, separados por vírgula",
                            IsDeleted = false,
                            Key = "sizes_available",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "P,M,G,G1,GG"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Provedor de WhatsApp: manual (link wa.me) ou nicochat (API)",
                            IsDeleted = false,
                            Key = "wp_provider",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "manual"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "URL base da API Nicochat (ex: https://api.nicochat.com)",
                            IsDeleted = false,
                            Key = "wp_nicochat_url",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ""
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "API Key da Nicochat",
                            IsDeleted = false,
                            Key = "wp_nicochat_key",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ""
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Template da mensagem para o cortador. Variáveis: {OrderNumber}, {Color}, {Variation}, {SizesBlock}, {Total}",
                            IsDeleted = false,
                            Key = "wp_template_cutter",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Pedido #{OrderNumber}\n{Color} {Variation}\n{SizesBlock}\nTotal: {Total} peças"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Template da mensagem para o costureiro. Variáveis: {OrderNumber}, {Color}, {Variation}, {Total}, {SizesBlock}, {Cost}",
                            IsDeleted = false,
                            Key = "wp_template_sewer",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Pedido {OrderNumber}\n{Color} {Variation} - {Total}\n{SizesBlock}\nTotal {Total} camisetas R${Cost}"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Template da mensagem para o fornecedor DTF. Variáveis: {Date}, {SheetsBlock}, {TotalSheets}, {TotalCost}",
                            IsDeleted = false,
                            Key = "wp_template_dtf",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Pedido DTF - {Date}\n{SheetsBlock}\nTotal: {TotalSheets} folha(s) — R${TotalCost}"
                        });
                });

            modelBuilder.Entity("SistemaTraction.Domain.Cutting.CuttingDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CuttingCostTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CuttingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveredPiecesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuttingOrderId")
                        .IsUnique();

                    b.ToTable("CuttingDeliveries", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Cutting.CuttingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FabricRollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendationBasedOnOrders")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendationDays")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedPiecesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedPiecesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FabricRollId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("CuttingOrders", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Dtf.DtfModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SheetCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SheetLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StampsPerSheet")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DtfModels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Angel",
                            SheetCost = 49.80m,
                            SheetLabel = "Folha 1",
                            StampsPerSheet = 9,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0002-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Flying Souls",
                            SheetCost = 49.80m,
                            SheetLabel = "Folha 2",
                            StampsPerSheet = 6,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0003-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Old Skull Tongue",
                            SheetCost = 49.80m,
                            SheetLabel = "Folha 3",
                            StampsPerSheet = 21,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0005-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Red Rage",
                            SheetCost = 49.80m,
                            SheetLabel = "Folha 5",
                            StampsPerSheet = 4,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0007-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Flaming Skull",
                            SheetCost = 49.80m,
                            SheetLabel = "Folha 7",
                            StampsPerSheet = 8,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0009-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Made in Traction",
                            SheetCost = 49.80m,
                            SheetLabel = "Folha 9",
                            StampsPerSheet = 5,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SistemaTraction.Domain.Dtf.DtfStockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("DtfModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DtfModelId")
                        .IsUnique();

                    b.ToTable("DtfStockItems", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Dtf.DtfStockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Delta")
                        .HasColumnType("int");

                    b.Property<Guid>("DtfStockItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DtfStockItemId");

                    b.ToTable("DtfStockMovements", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Fabric.FabricColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FabricTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HexCode")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FabricTypeId");

                    b.ToTable("FabricColors", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Fabric.FabricRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FabricColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FabricTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerKgActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("FabricColorId");

                    b.HasIndex("FabricTypeId");

                    b.ToTable("FabricRolls", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Fabric.FabricType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageKgPerRoll")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("AveragePiecesPerRoll")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Variation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Variation")
                        .IsUnique();

                    b.ToTable("FabricTypes", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Financial.FinancialEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("EntryDate");

                    b.HasIndex("ReferenceId");

                    b.ToTable("FinancialEntries", (string)null);
                });

            modelBuilder.Entity("SistemaTraction.Domain.Separation.SeparationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DtfModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SeparationListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DtfModelId");

                    b.HasIndex("SeparationListId");

                    b.ToTable("SeparationItems");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Separation.SeparationList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SeparationLists");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Separation.SkuCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DtfModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SkuCodes");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Sewing.SewingDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CuttingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DefectCostTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DefectivePiecesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoodPiecesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("SewingCostTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuttingOrderId")
                        .IsUnique();

                    b.ToTable("SewingDeliveries");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Stock.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FabricColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FabricColorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FabricTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FabricTypeVariation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FabricColorId", "Size")
                        .IsUnique();

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Cutting.CuttingDelivery", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Cutting.CuttingOrder", "CuttingOrder")
                        .WithMany()
                        .HasForeignKey("CuttingOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuttingOrder");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Cutting.CuttingOrder", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Fabric.FabricRoll", "FabricRoll")
                        .WithMany()
                        .HasForeignKey("FabricRollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FabricRoll");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Dtf.DtfStockItem", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Dtf.DtfModel", "DtfModel")
                        .WithOne()
                        .HasForeignKey("SistemaTraction.Domain.Dtf.DtfStockItem", "DtfModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DtfModel");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Dtf.DtfStockMovement", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Dtf.DtfStockItem", "DtfStockItem")
                        .WithMany("Movements")
                        .HasForeignKey("DtfStockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DtfStockItem");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Fabric.FabricColor", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Fabric.FabricType", "FabricType")
                        .WithMany("Colors")
                        .HasForeignKey("FabricTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FabricType");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Fabric.FabricRoll", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Fabric.FabricColor", "FabricColor")
                        .WithMany()
                        .HasForeignKey("FabricColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTraction.Domain.Fabric.FabricType", "FabricType")
                        .WithMany()
                        .HasForeignKey("FabricTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FabricColor");

                    b.Navigation("FabricType");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Separation.SeparationItem", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Dtf.DtfModel", "DtfModel")
                        .WithMany()
                        .HasForeignKey("DtfModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaTraction.Domain.Separation.SeparationList", "SeparationList")
                        .WithMany("Items")
                        .HasForeignKey("SeparationListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DtfModel");

                    b.Navigation("SeparationList");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Sewing.SewingDelivery", b =>
                {
                    b.HasOne("SistemaTraction.Domain.Cutting.CuttingOrder", "CuttingOrder")
                        .WithMany()
                        .HasForeignKey("CuttingOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuttingOrder");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Dtf.DtfStockItem", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Fabric.FabricType", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("SistemaTraction.Domain.Separation.SeparationList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
